### PR TITLE
Schema foldering support

### LINKED ISSUE #111: Schema Foldering support
I'd like to be able to sort entity models into folders by their scheme name.

### PR DESCRIPTION
**Pull request by JohnGoldInc**
This provides for the ability to folder Entities by the schema of the tables,
And keeps class naming to the same standard of capability.

Closes #111

### CODE REVIEW

**Comment by tonysneed** [comment]
@JohnGoldInc As I described in #99, I don't think schema foldering has anything to do with transformers, and you should not have to use them in order to add the schema folders.

Instead, I think a preferable approach would be to add an `EnableSchemaFolders` property to `ReverseEngineerOptions` so that you can set it to true in `ConfigureDesignTimeServices` when calling `services.AddHandlebarsScaffolding`.

What do you think?

**Comment by JohnGoldInc** [comment]
I was thinking that way because they might want to play with class name too
and gives most utility to the dev ( without making changes to handlebars
scaffolding)

**Comment by tonysneed** [comment]
It won't be difficult to add transformers support via arguments for `services.AddHandlebarsTransformers`. That can be a separate PR.

It would be great if you could create a new PR from scratch that takes the approach I suggested. To do this create a new branch from the latest commit on my master branch (5b2d3d24). Use this branch for your new PR.

For some guidance on creating the PR, please refer to the [Contributing Guidelines](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/.github/CONTRIBUTING.md).

**Comment by JohnGoldInc** [comment]
@tonysneed Ok was looking at ReverseEngineerOptions it would have to change to be a binary pipe concatenated.

So the original code:
```
    public enum ReverseEngineerOptions
    {
        /// <summary>
        /// Generate DbContext class only.
        /// </summary>
        DbContextOnly,

        /// <summary>
        /// Generate entity type classes only.
        /// </summary>
        EntitiesOnly,

        /// <summary>
        /// Generate both DbContext and entity type classes.
        /// </summary>
        DbContextAndEntities
    }
```
would become : 

```
    public enum ReverseEngineerOptions
    {
        /// <summary>
        /// Generate DbContext class only.
        /// </summary>
        DbContextOnly = 1,

        /// <summary>
        /// Generate entity type classes only.
        /// </summary>
        EntitiesOnly = 2,

        /// <summary>
        /// Generate both DbContext and entity type classes.
        /// can also use syntax 'ReverseEngineerOptions.DbContextOnly | ReverseEngineerOptions.EntitiesOnly '
        /// </summary>
        DbContextAndEntities = 1 + 2,

        /// <summary>
        /// Generate schema folders for entity type classes
        /// i.e. 'ReverseEngineerOptions.DbContextAndEntities | ReverseEngineerOptions.EnableSchemaFolders '
        /// </summary>
        EnableSchemaFolders = 4,
    }
```

And code changed to test via binary matching instead of equivalency throughout project.

Sound Good?

**Comment by JohnGoldInc** [comment]
@tonysneed And regarding #99  "EnableNullableReferenceTypes = 8" because the numbering needs to an exponent of 2

**Comment by tonysneed** [comment]
@JohnGoldInc Sorry, I meant `HandlebarsScaffoldingOptions`, not `ReverseEngineerOptions`.

**Pull request closed without merging**
