### PR TITLE
Ability to exclude tables, use embedded templates, and supply TemplateData

### PR DESCRIPTION
**Pull request by greggbjensen**
We are using this Scaffolding with microservices, and as part of that we needed a few additional capabilities.  These have been added as below:

- Ability to exclude tables by name or schema and name from scaffolding
- Ability to embed handlebar templates in an assembly that can be added to many projects
- Ability to pass in global TemplateData for use within any template
- Options changed to class to support additional settings

### CODE REVIEW

**Comment by tonysneed** [comment]
Thanks — I look forward to looking at this!

**Comment by cyberknet** [comment]
Any movement on this one? I'd really love to see the option to exclude tables come to fruition. I have just a couple of tables that need to be excluded, and currently a long list of -t on the command line as a result :) I see that the branch now has conflicts - do you need help cleaning the conflicts up, or is there more this is waiting on to be merged?

**Comment by tonysneed** [comment]
Sorry, I must have missed this one. I'll be sure to have a look and, if it looks good, merge into the next release.

**Comment by tonysneed** [comment]
Replaced by #88, which resolves merge conflicts.

**Pull request closed without merging**
