### PR TITLE
Including table and column description metadata

### PR DESCRIPTION
**Pull request by MarkAtRamp51**
# Including Table and Column Descriptions

Two new handlebars tokens were added to allow for the use of {{comment}} on table templates and {{property-comment}} on property templates.  This can be useful to incorporate into xml doc comments to pull database descriptions into intellisense.

Apologies for the commit history, the more i tried to clean it up, the worse it became.  I need some more practice there I guess.  The Author should be MarkAtRamp51.

### CODE REVIEW

**Comment by ErikEJ** [comment]
FYI, the latest daily build of EF Core Power Tools now always scaffolds entity and property comments as summary XML

**Comment by MarkAtRamp51** [comment]
Awesome.  Thanks.  Will this get merged?

**Comment by tonysneed** [comment]
Going to check this out tomorrow. Thanks so much for the PR!

**Comment by tonysneed** [comment]
Used this script to add table and column comments in T-SQL.

```sql
-- Add a comment to a table Customer
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'hello table Customer' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'Customer'

-- Adding a comment to a column CompanyName for the table Customer
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'hello CompanyName' ,@level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'Customer', @level2type=N'COLUMN', @level2name=N'CompanyName'
```

**Comment by tonysneed** [comment]
@MarkAtRamp51 Are you able to make the changes I requested?

**Comment by MarkAtRamp51** [comment]
@tonysneed I am, and I want to.  I just haven't been able to get to it yet.  I'll see if I can get them over to you by monday.

**Comment by MarkAtRamp51** [comment]
@tonysneed I think I have your requested changes in there.  I tried to squash a few times and had some major troubles.  I think pulling master in added some more complexity to it, resulting in a lot more commits to try and squash.  Let me know if you have any advice.   Sorry, I've never used rebase too much.

**Comment by tonysneed** [comment]
@MarkAtRamp51 A lot of commits have beed added to the master branch since you created your PR. And in the meantime I have also created [Contributing Guidelines](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/.github/CONTRIBUTING.md) for this repo, which have step-by-step instructions and [video tutorial](https://youtu.be/gxhbH9fzTDo) for following GitHub's fork and pull model of collaboration.

So at this point I would suggest you [rename](https://help.github.com/en/github/administering-a-repository/renaming-a-repository) your fork (so as to preserve your work), then re-fork this repo. Then your will have a master branch with the latest commits. At this point, **carefully follow steps in the Contributing Guidelines**. Begin by cloning your fork and creating a _local feature branch_. Then commit your updates and create a _new pull request_ to replace this one.

At that point, _I will review and approve your new PR_. If there are new commits that I have pushed to master, you can apply Step 15 to sync your fork. If your branch has multiple commits, you can try interactive rebase to squash them.

**Comment by MarkAtRamp51** [comment]
Ok. I'll work on it.

**Pull request closed without merging**
