### PR TITLE
Contains enhancements for the navigation properties

### LINKED ISSUE #160: Enhancements For Navigation Properties
Right now, when trying to filter navigation properties for transformation, we only have access to certain properties such as name, type and nullability. 

I propose introducing a "NavigationPropertyInfo" class that derives from "EntityPropertyInfo". It will contain an "INavigation Navigation" property so that users of the library will not be limited to certain properties of the original EF Core navigation. This will increase the extensibility of the project. It will also benefit the templating since users will have access to all properties of the navigation object.

I've already done some work in that regard. I am planning to open a PR for this issue.

### PR DESCRIPTION
**Pull request by john-larson**
Right now, when trying to filter navigation properties for transformation, we only have access to certain properties such as name, type and nullability.

This change is introducing a "NavigationPropertyInfo" class that derives from "EntityPropertyInfo". It contains an "INavigation Navigation" property so that users of the library will not be limited to certain properties of the original EF Core navigation. This will increase the extensibility of the project. It will also benefit the templating since users will have access to all properties of the navigation object.

Closes #160

### CODE REVIEW

**Comment by tonysneed** [comment]
Thanks for your PR. It looks like a number of unit tests are failing. Could you please fix those?

Also, it would be good to have some tests to ensure everything is working as it should.

Lastly, I did try running the ScaffoldingSample with `services.AddHandlebarsTransformers`, but there were errors in the ctor of generated entities, as well as a problem with nullable nav properties.

**Comment by JohnGoldInc** [comment]
There were only 27 passing tests in the branch I ran off, think core
stopped caring about annotation switch? Same 27 kept working, but I can add
more tests soon

**Comment by JohnGoldInc** [comment]
Oops wrong thread

**Comment by tonysneed** [comment]
@john-larson I pulled commit 19444cf from upstream into your branch, so it's up-to-date with changes I made in the main repo. However, there are some tests that are failing in [HbsTypeScriptScaffoldingGeneratorTests](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/test/Scaffolding.Handlebars.Tests/HbsTypeScriptScaffoldingGeneratorTests.cs). Would you please be so kind as to fix those tests so that they pass?

As I mentioned above, I ran the **ScaffoldingSample** with `services.AddHandlebarsTransformers`.

```csharp
// Add optional Handlebars transformers
services.AddHandlebarsTransformers(
    entityNameTransformer: n => n + "Foo",
    entityFileNameTransformer: n => n + "Foo",
    constructorTransformer: e => new EntityPropertyInfo(e.PropertyType + "Foo", e.PropertyName + "Foo"),
    propertyTransformer: e => new EntityPropertyInfo(e.PropertyType, e.PropertyName + "Foo"),
    navPropertyTransformer: e => new NavigationPropertyInfo(e.PropertyType + "Foo", e.PropertyName + "Foo"));
```

There were errors in the ctor of generated entities, as well as a problem with nullable nav properties. For example:

```csharp
public partial class CustomerFoo : EntityBase // My Handlebars Helper
{
    public CustomerFoo()
    {
        // Error in the name of the transformed Orders navigation property
        OrdersFooFoo = new HashSet<OrderFooFoo>();
    }

    public string CustomerIdFoo { get; set; } = default!;
    public string CompanyNameFoo { get; set; } = default!;
    public string? ContactNameFoo { get; set; } = default!;
    public string? CityFoo { get; set; } = default!;
    public string? CountryFoo { get; set; } = default!;

    // Error in nullable navigation property
    public virtual CustomerSetting?Foo CustomerSettingFoo { get; set; }
    public virtual ICollection<OrderFoo> OrdersFoo { get; set; } = default!;
}
```

If you fix these issues, I'll be happy to merge your PR. Thanks!

**Comment by skuami** [comment]
@john-larson I could solve my issue with your current branch. It would be great if @tonysneed could merge your PR. Currently I don't have the time to look into your code and fix the issues mentioned by Tony.

**Comment by tonysneed** [comment]
I will have some time tomorrow to try to fix the failing tests.

**Comment by skuami** [comment]
No hurry - I am using currently my own compiled nuget package and it works. But I don't wont to lose the compatibility to the original source. 
So whenever someone has time - that's fine with me. ;-)

**Comment by tonysneed** [comment]
Will re-open this PR if @john-larson, @skuami or someone else can fix the issues and add tests.

**Pull request closed without merging**
