### PR TITLE
Changes to Support Schema Foldering, And Nullable EF Core Project

### PR DESCRIPTION
**Pull request by JohnGoldInc**
Changes to Support Schema Foldering, And Nullable EF Core Project Using propertyTransformer: (epi) => new EntityFrameworkCore.Scaffolding.Handlebars.EntityPropertyInfo(epi.PropertyType + (epi.PropertyIsNullable == true && !epi.PropertyType.Contains("?") ? "?" :"") , epi.PropertyName, epi.PropertyIsNullable)

### CODE REVIEW

**Comment by johngold-onshift** [comment]
@tonysneed Any feedback?

**Comment by tonysneed** [comment]
@johngold-onshift The way I think we want to approach adding support for nullable reference types is to add an `EnableNullableReferenceTypes` property to `ReverseEngineerOptions` so that you can set it to true in `ConfigureDesignTimeServices` when calling `services.AddHandlebarsScaffolding`.

```csharp
public void ConfigureDesignTimeServices(IServiceCollection services)
{
    services.AddHandlebarsScaffolding(options =>
    {
        options.EnableNullableReferenceTypes = true;
    });
}
```

Then in `HbsCSharpEntityTypeGenerator.GenerateProperties` check `property.IsNullable` to add a '?' to properties that are nullable in the database.

Metadata will need to be added, so that the Properties.hbs template can be modified to set defaults for non-nullable properties and generate output that uses the null forgiving operator.

```csharp
public partial class Customer
{
    public string CompanyName { get; set; } = default!;
}
```

Would you be able to create a new PR that takes this approach?

**Comment by tonysneed** [comment]
For schema foldering support, would you create another issue and a separate PR? Thanks!

**Comment by johngold-onshift** [comment]
Yes, just got distracted today :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tonysneed** [comment]
@JohnGoldInc Be sure to create a new branch from the latest commit on my master branch (5b2d3d24). Use this branch for your new PR.

For some guidance on creating the PR, please refer to the [Contributing Guidelines](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/.github/CONTRIBUTING.md).

**Comment by JohnGoldInc** [comment]
@tonysneed For EnableNullableReferenceTypes ; do you want me to check in changes to sample project ? (where I am testing it)

**Comment by tonysneed** [comment]
Yes I think that is a good idea to check in changes to the sample project. That way, I can also run it on my side to see if I get the same behavior.

**Comment by JohnGoldInc** [comment]
@tonysneed I deleted CodeTemplates folder to let it regenerate; I see it would want to remove things like:
 // Comment
// My Handlebars Block Helper
{{my-helper}}

I assume you would want me to put that back?

**Comment by tonysneed** [comment]
Oh yes, don't delete the templates.

**Pull request closed without merging**
