### PR TITLE
[Feature] Update to EF Core 5.0

### PR DESCRIPTION
**Pull request by tonysneed**
**Changes**
Update to EF Core 5.0 RC2
    - Remove EnablePluralization.
    - Enable suppression of OnConfiguring.

**Related Issues**
Addresses #129 

**NuGet Package**
https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars/5.0.0-rc.2

### CODE REVIEW

**Comment by ErikEJ** [comment]
Assume there are breaking changes in templates?

**Comment by ErikEJ** [comment]
Re: 
- Remove EnablePluralization.
- Enable suppression of OnConfiguring.

Will the library just respect the general options for this now?

**Comment by tonysneed** [comment]
@ErikEJ Yes, all the template files have been updated. I took pluralization out because it’s in the CLI, and suppression of OnConfiguring is respected.

**Comment by ErikEJ** [comment]
Added to latest daily build of EF Core Power Tools!

**Comment by ErikEJ** [comment]
Great, will update to RTM soon

**Pull request merged**
