### PR TITLE
Schema Foldering support

### LINKED ISSUE #111: Schema Foldering support
I'd like to be able to sort entity models into folders by their scheme name.

### PR DESCRIPTION
**Pull request by JohnGoldInc**
Closes #111

### CODE REVIEW

**Comment by tonysneed** [comment]
In order to merge this PR, I will need you to sync your PR branch, since it is behind by several commits. Please follow the instructions in **Item 15** to _sync your fork_ from the [Contributing Guidelines](https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars/blob/master/.github/CONTRIBUTING.md#create-pull-request).

**Comment by JohnGoldInc** [comment]
@tonysneed should be good now

**Comment by tonysneed** [comment]
Did you force push your branch? I don't see any change in the history of your [feature branch](https://github.com/JohnGoldInc/EntityFrameworkCore.Scaffolding.Handlebars/commits/%40feature/Schema_Foldering_support_%23111). The last 4 commits from the stream repo are missing.

**Comment by JohnGoldInc** [comment]
Sigh, I'll try again. git command line is not fun, need to download a better gui

**Comment by tonysneed** [comment]
With Git I have found that, because it was originally written as a command line tool, there are certain things which are turn out to be easier if you do them from the command line.

That said, I understand it is a learning process, especially some of the advanced techniques like interactive rebase.

For this PR, I can cherry pick your commit and just merge it to master.

**Comment by tonysneed** [comment]
Merged commit 9b447245.

**Comment by johngold-onshift** [comment]
Thank You!

**Comment by JohnGoldInc** [comment]
Thank You!

**Pull request closed without merging**
